name: auraq
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_islamic_icons: ^1.0.2
  google_fonts: ^8.1.0
  font_awesome_flutter: ^11.0.0
  cached_network_image: ^3.4.1
  intl: ^0.20.2
  riverpod: ^3.3.2
  flutter_riverpod: ^3.3.2
  hijri: ^3.0.1
  geolocator: ^14.0.3
  adhan_dart: ^2.0.1
  permission_handler: ^12.0.3
  hive: ^2.2.3
  quran: ^1.4.1
  hive_flutter: ^1.1.0
  just_audio: ^0.9.42
  just_audio_background: ^0.0.1-beta.17
  path_provider: ^2.1.3
  dio: ^5.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app_logos/auraq_logo.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/app_logos/auraq_logo.png
