class QuranUtils {
  static const List<String> juzNamesArabic = [
    "آلم",
    "سَيَقُولُ",
    "تِلْكَ الرُّسُلُ",
    "لَنْ تَنَالُوا",
    "وَالْمُحْصَنَاتُ",
    "لَا يُحِبُّ اللَّهُ",
    "وَإِذَا سَمِعُوا",
    "وَلَوْ أَنَّنَا",
    "قَالَ الْمَلَأُ",
    "وَاعْلَمُوا",
    "يَعْتَذِرُونَ",
    "وَمَا مِنْ دَابَّةٍ",
    "وَمَا أُبَرِّئُ",
    "رُبَمَا",
    "سُبْحَانَ الَّذِي",
    "قَالَ أَلَمْ",
    "اقْتَرَبَ لِلنَّاسِ",
    "قَدْ أَفْلَحَ",
    "وَقَالَ الَّذِينَ",
    "أَمَّنْ خَلَقَ",
    "اتْلُ مَا أُوحِيَ",
    "وَمَنْ يَقْنُتْ",
    "وَمَا لِيَ",
    "فَمَنْ أَظْلَمُ",
    "إِلَيْهِ يُرَدُّ",
    "حم",
    "قَالَ فَمَا خَطْبُكُمْ",
    "قَدْ سَمِعَ اللَّهُ",
    "تَبَارَكَ الَّذِي",
    "عَمَّ يَتَسَاءَلُونَ",
  ];

  static const List<String> juzNamesEnglish = [
    "Alif Lam Meem",
    "Sayaqool",
    "Tilkal Rusul",
    "Lan Tanalu",
    "Wal Muhsanat",
    "La Yuhibbullah",
    "Wa Iza Samiu",
    "Wa Law Annana",
    "Qalal Mala'u",
    "Wa'lamu",
    "Ya'taziroon",
    "Wa Ma Min Dabbatin",
    "Wa Ma Ubarri'u",
    "Rubama",
    "Subhanallazi",
    "Qala Alam",
    "Iqtaraba Linnasi",
    "Qad Aflaha",
    "Wa Qalal Lazina",
    "Amman Khalaqa",
    "Utlu Ma Uhiya",
    "Wa Man Yaqnut",
    "Wa Ma Liya",
    "Fa Man Azlamu",
    "Ilaihi Yuraddu",
    "Ha Meem",
    "Qala Fama Khatbukum",
    "Qad Samiallah",
    "Tabarakallazi",
    "Amma Yatasa'aloon",
  ];
}
